[Moore] Specify -attrdefs-dialect when generating attributes, NFC.
This flag appears to be needed to support an upcoming revision of
LLVM. Without this, TableGen complains with:

```
error: defs belonging to more than one dialect. Must select one via
'--(attr|type)defs-dialect'
```