[ExportVerilog][NFC] Fix missing NOLINTEND.
Found by tidy:

error: unmatched 'NOLINTEND' comment without a previous 'NOLINTBEGIN' comment [clang-tidy-nolint]